### ISSUE TITLE
Replace single \n with whitespace

### ISSUE THREAD

**Issue by grigorii-horos** [stevenvachon/normalize-html-whitespace#1]
Now single `\n` remains unchanged, but I think that will be good if it will be replaced with whitespace.

**Comment by mvasilkov** [comment]
@horosgrisa yup. The spec says, at least [here][1]:

> replace any sequence of **one or more** consecutive code points that are ASCII whitespace in the string with a single U+0020 SPACE code point

[1]: https://infra.spec.whatwg.org/#strip-and-collapse-ascii-whitespace
